### PR TITLE
Anaconda package

### PR DESCRIPTION
**Pull request by lkagami**

### CODE REVIEW

**Comment by ssalentin** [comment]
As I understand it, setting up the conda package requires two additional files:

`meta.yaml` and `build.sh`.

In your branch, all of the PLIP code is duplicated in conda_plip, which is not desirable.
Could you remove the duplicate code and change the setup to use the existing modules?

**Comment by lkagami** [comment]
Please make sure it is correct.

**Comment by lkagami** [comment]
Yes, it is possible. However I had to add the lines containing "def main_init ():". Thanks.

**Comment by lkagami** [comment]
Yes, it is possible. However I had to add the lines containing "def main_init ():".

**Pull request merged**
